### ISSUE TITLE
Cannot connect to notebook - `sparkling-tree-dvvd-ydxba`

### ISSUE THREAD

**Issue by just-cic** [phpsandbox/phpsandbox#35] opened 2022-12-27 09:26 UTC
### **How can we reproduce it?**

1. Create standard notebook '...'
3. See an error Connection to notebook failed!

### **Expected results**
I expect to see my project files and be able to do a compilation

### **Actual Behavior**
An error shows up

### **Screenshots or Screencast**
![image](https://user-images.githubusercontent.com/32402664/209644617-425fb42f-55c4-4ca9-8164-653826e4e722.png)

**More notes or context or questions**

**Notebook details**
|Notebook type|URL|PHP version|
|-|-|-|
|standard|[ydxba](https://phpsandbox.io/n/ydxba)|8.1|

**Comment by bosunski** [comment] 2023-01-05 17:15
Closing this because the issue is resolved.

**Closed as completed by bosunski** 2023-01-05 17:15 UTC
