### ISSUE TITLE
Not usable on Safari

### ISSUE THREAD

**Issue by Felix-Weber** [phpsandbox/phpsandbox#4] opened 2021-07-17 09:13 UTC
### **Description of Bug**
On Safari the box "Interactive Notebook" on https://phpsandbox.io/n/<xx> is not usable, as it is hidden behind the title bar of that box.

### **How can we reproduce it?**

1. Create standard notebook 'Broad Sun'
2. Click on 'Anything'
3. See an error Box not usable

### **Actual Behavior**
A clear and concise description of what happened.

### **Screenshots or Screencast**
See an error Box not usable
<img width="1439" alt="Bildschirmfoto 2021-07-17 um 10 58 37" src="https://user-images.githubusercontent.com/2399392/126031968-564aa738-4bca-433c-9678-1e943ef10341.png">

**More notes or context or questions**
Version 14.0.2 (16610.3.7.1.9)
MacOS 11.1 (20C69)
MacBook Pro (13-inch, M1, 2020)

**Comment by mercyikpe** [comment] 2021-07-21 13:41
Hi, @lixam  Thanks for pointing this out, am currently working on this.

**Comment by mercyikpe** [comment] 2021-07-23 15:46
Hi @lixam I've pushed a fix for the issue you encountered here. The fix places the Run button at the top instead of the bottom to avoid the button being covered by the footer.

You mentioned an "error Box not usable" on Safari, I tested the app on Safari, Brave, Chrome and Firefox but could not reproduce the error box, could you send me a screenshot of the error box?

Thanks!

**Comment by Felix-Weber** [comment] 2021-07-25 10:08
Hey @mercyikpe,

sorry for my bad grammar: the issue is that the notebook box is not visible. Have a look:
![q5c7T96kh0](https://user-images.githubusercontent.com/2399392/126895456-b400651a-c0de-4c7f-a52f-c715a7a11b5c.gif)

So I cannot write any code. Hope this makes my issue a bit clearer.

**Comment by mercyikpe** [comment] 2021-07-26 12:07
This is so helpful, am looking at it now.
Thank you!!!

**Comment by mercyikpe** [comment] 2021-08-02 09:34
Hi @lixam I tried recreating this issue, tried on multiple browsers and screen size but could not recreate this issue. While I do more research on how to reproduce and fix this issue, I've pushed an update for the editor area to work better. 
Thanks for reporting this. I'll keep you posted on the progress regarding this issue.

**Comment by fvignals** [comment] 2021-09-15 12:27
There are a big problem on this page:

I tried to debug css: many html elements in serif OS font-family (Time news roman for windows)
then many latency, in my mind due to js. : waiting, ... waiting 
too many css rules: near 30,000.
too many multiple css rules: many opposite rules for the same element.
And a many bug for font-family.

when I start developer mode on Firefox or chrome is pretty latency due to your js ?
sorry but too latency for more informations. GG for your work.

**Comment by mercyikpe** [comment] 2021-10-11 17:59
@fvignals We will look into this and find ways to fix the bugs and reduce waiting time.

**Comment by mercyikpe** [comment] 2021-10-11 18:03
@lixam unfortunately, I haven't been able to reproduce this issue on Safari and other browsers. 
I'll update you on any progress made regarding this issue.

Thank you!

**Comment by Felix-Weber** [comment] 2021-10-11 18:57
@mercyikpe mmh, maybe it is the resolution? Because on my iMac it is working fine. And that iMac has a lower resolution than the Macbook M1:
<img width="310" alt="Bildschirmfoto 2021-10-11 um 20 57 24" src="https://user-images.githubusercontent.com/2399392/136842512-4ccef0de-1f99-46be-b620-91e1f1739611.png">

Just an idea...

**Closed as not planned** 2022-07-04 23:24 UTC
