### ISSUE TITLE
Cannot connect to notebook - `demophp-7r3na`

### ISSUE THREAD

**Issue by Tanve-rsajib** [phpsandbox/phpsandbox#34] opened 2022-12-26 18:14 UTC
### **How can we reproduce it?**

1. Create standard notebook '...'
3. See an error ...

### **Actual Behavior**
A clear and concise description of what happened.

### **Screenshots or Screencast**
You can add screenshots or screen records of the issue.

**More notes or context or questions**

**Notebook details**
|Notebook type|URL|PHP version|
|-|-|-|
|interactive|[7r3na](https://phpsandbox.io/n/7r3na)|8.1|

**Comment by bosunski** [comment] 2023-01-05 17:16
Closing this because the issue is resolved.

**Closed as completed by bosunski** 2023-01-05 17:16 UTC
